version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: uno_mongo
    command:
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongopasswd
    volumes:
      - mongo_data:/data/db
    networks:
      - uno_network

  redis:
    image: redis:alpine
    container_name: uno_redis
    ports:
      - "6379:6379"
    networks:
      - uno_network
    healthcheck:
      interval: 5s
      timeout: 30s
      retries: 50

  uno-server:
    build: .
    container_name: uno_app
    restart: always
    ports:
      - "${PORT}:${PORT}" # PORT from .env
    environment:
      - PORT=${PORT} # PORT from .env
      - MONGO_URI=mongodb://mongoadmin:mongopasswd@mongo:27017/?authSource=admin # Fixed for Docker network
      - REDIS_HOST=redis # Fixed for Docker network
      - REDIS_PORT=${REDIS_PORT} # REDIS_PORT from .env
      - JWT_SECRET=${JWT_SECRET} # JWT_SECRET from .env
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET} # JWT_REFRESH_SECRET from .env
    depends_on:
      - mongo
      - redis
    networks:
      - uno_network

  mongo-express:
    image: mongo-express
    container_name: uno_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongopasswd
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_EXPRESS_USERNAME} # ME_EXPRESS_USERNAME from .env
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_EXPRESS_PASSWORD} # ME_EXPRESS_PASSWORD from .env
    depends_on:
      - mongo
    networks:
      - uno_network

volumes:
  mongo_data:

networks:
  uno_network:
